import Head from "next/head";
import Layout from "../components/Layout";
import { TOKEN, DATABASE_ID } from "../config";
import ProjectItem from "@/components/projects/project-item";

export default function Projects({ projects }) {
  return (
    <Layout>
      <Head>
        <title>JaeIn Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/react.png" />
      </Head>

      <div className="flex flex-col items-center">
        <span className="m-3 flex font-semibold text-xl">
          총 프로젝트 : {projects.results?.length}개
        </span>

        <div className="grid grid-cols-1 md:grid-cols-2">
          {projects.results?.map((x) => (
            <ProjectItem data={x} key={x.id} />
          ))}
        </div>
      </div>
    </Layout>
  );
}

export async function getStaticProps() {
  const options = {
    method: "POST",
    headers: {
      Accept: "application/json",
      "Notion-Version": "2022-02-22",
      "Content-Type": "application/json",
      Authorization: `Bearer ${TOKEN}`,
    },
    body: JSON.stringify({
      sorts: [
        {
          property: "Name",
          direction: "ascending",
        },
      ],
      page_size: 100,
    }),
  };

  const res = await fetch(
    `https://api.notion.com/v1/databases/${DATABASE_ID}/query`,
    options
  );

  const projects = await res.json();

  return {
    props: { projects },
    revalidate: 1, // will be passed to the page component as props
    // getStaticProps() 메소드를 사용한다면 revalidate 로 데이터 변경시 갱신가능!
    // revalidate: 1 // 데이터 변경이 있으면 갱신 1초 마다
  };
}
